.Dd $Mdocdate: November 17 2012 $
.Dt GIT-AUTH 1
.Os
.Sh NAME
.Nm git-auth
.Nd authorize git commands
.Sh SYNOPSIS
.Nm GIT_AUTH_ID=ID git-auth COMMAND [ARGS ...]
.Sh DESCRIPTION
.Nm
starts by reading rules from /etc/git/auth.conf, one rule per line.
Empty lines and lines starting with # are ignored.
Each rule is made of tokens separated by one or more spaces.
.Pp
.Nm
executes COMMAND and ARGS using execvp if the requested ID, COMMAND and ARGS
match any of the rules defined in /etc/git-auth.conf.
.Pp
.Nm
matches a rule by matching all the rule's tokens with
ID, COMMAND and ARGS in order. Comparison is case sensitive.
.Pp
A wildcard token "*" matches any string.
.Sh ENVIRONMENT
GIT_AUTH_ID :
an arbitrary token to match with the rules.
This is usually set for each public key in /home/git/.ssh/authorized_keys
with
.Nm environment="GIT_AUTH_ID=..."
.Sh FILES
/etc/git/auth.conf
.Pp
/home/git/.ssh/authorized_keys
